[versions]
# minSdk = "21" из-за skolson для zip распаковки поднято до 26
minSdk = "26"
targetSdk = "35"
compileSdk = "36"
javaVersion = "17"
desktopJavaVersion = "21"

ksp_version="2.2.20-2.0.4"
kotlin_version="2.2.20"
kotlin_serialization_version="1.9.0"
kotlinx_io_version="0.8.2"
kotlin_coroutines_version="1.10.2"
koin="4.1.1"
nav_version="2.9.6"
kmp_nav_version="2.9.1"
kmp_lifecycle_version="2.9.6"
agp_version="8.9.2"
room_version="2.8.4"
androidx_sqlite_version="2.6.1"
work_version="2.10.2"
compose_bom_version="2025.11.00"
compose_kmp_plugin_version="1.9.3"
compose_compiler_gradle_plugin_version="2.2.21"
junitVersion = "4.13.2"
junit = "1.3.0"
espressoCoreVersion = "3.7.0"
gson_version = "2.11.0"
filekit_version = "0.12.0"
kmpio_version = "0.2.3"
androidx_work_version = "2.11.0"
coroutines_guava_version = "1.10.2"
kotlinTestVersion = "2.2.20"
runnerVersion = "1.7.0"
coreVersion = "1.7.0"
napier_version = "2.7.1"
kodeview_version = "0.9.0"
text_to_speech_version = "3.0.0"

[libraries]
# provides the Kotlin Gradle plugin
# This plugin enables Gradle to understand and compile Kotlin code,
# regardless of the target platform (JVM, Android, Multiplatform).
gradleplugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
gradleplugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp_version" }
gradleplugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose_kmp_plugin_version" }
gradleplugin-compose-compiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "compose_compiler_gradle_plugin_version" }
gradleplugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp_version" }

androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-preference = "androidx.preference:preference-ktx:1.2.1"
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx_work_version" }
# await для WorkManager
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref="coroutines_guava_version" }


androidx-core-ktx = "androidx.core:core-ktx:1.16.0"

# (Java only)
androidx-work = { group = "androidx.work", name = "work-runtime", version.ref = "work_version" }

# navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "nav_version" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "nav_version" }

# result api
androidx-activity-ktx = "androidx.activity:activity-ktx:1.10.1"
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.8.8"

# room (kmp)
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx_sqlite_version" }
# Optional SQLite Wrapper available in version 2.8.0 and higher
# androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room_version" }

# Compose (only Android)
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom_version" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose" }

# kmp
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "kmp_nav_version" }

# Viewmodel
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "kmp_lifecycle_version" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "kmp_lifecycle_version" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "kmp_lifecycle_version" }

# Android misc
android-support-multidex = "com.android.support:multidex:1.0.3"
google-android-material = "com.google.android.material:material:1.4.0"

# TODO еще актуально?
apache-commons = "org.apache.commons:commons-lang3:3.9"

# kotlinx
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin_coroutines_version" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin_coroutines_version" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref="kotlin_serialization_version" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref="kotlin_serialization_version" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx_io_version" }
# kotlin kmp
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin_version" }
# desktop jvm
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlin_coroutines_version" }

# kmp logging
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier_version" }

kodeview = { group = "dev.snipme", name = "kodeview", version.ref = "kodeview_version" }

text-to-speech = { module = "nl.marc-apps:tts", version.ref = "text_to_speech_version" }

# Stetho core
facebook-stetho = "com.facebook.stetho:stetho:1.5.1"

# rxjava
reactivex-rxjava = "io.reactivex.rxjava2:rxjava:2.2.17"
reactivex-rxjava-rxandroid = "io.reactivex.rxjava2:rxandroid:2.1.1"
reactivex-rxjava-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.10.2"

# koin
koin-core = { module = "io.insert-koin:koin-core", version.ref="koin" }
# TODO remove
koin-android = { module = "io.insert-koin:koin-android", version.ref="koin" }
# workmanager
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref="koin" }

# koin compose  to your multiplatform application, for use Koin & Compose API
koin-compose = { module = "io.insert-koin:koin-compose", version.ref="koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref="koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref="koin" }

# If you are using pure Android Jetpack Compose, you can go with
# TODO remove
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref="koin" }
# TODO remove
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation", version.ref="koin" }

# koin annotations
# koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin_annotations_version" }
# koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin_annotations_version" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson_version" }


# retrofit
squareup-retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
squareup-retrofit-converter-gson = "com.squareup.retrofit2:converter-gson:2.9.0"
squareup-okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
squareup-okhttp-logging-interceptor = "com.squareup.okhttp:logging-interceptor:2.6.0"
squareup-retrofit-adapter-rxjava = "com.squareup.retrofit2:adapter-rxjava2:2.4.0"
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }

# filekit
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit_version" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit_version" }

# for zip files
kmpio = { module = "io.github.skolson:kmp-io", version.ref = "kmpio_version" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTestVersion" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runnerVersion" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "coreVersion" }
# kmpio-zip = { module = "io.skosi.kmpio:zip", version.ref = "kmpio_zip_version" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
room = { id = "androidx.room", version.ref = "room_version" }
android-application = { id = "com.android.application", version.ref = "agp_version" }
android-library = { id = "com.android.library", version.ref = "agp_version" }
#  to enable Kotlin support specifically for Android development
android-kotlin-support = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin_version" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp_version" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose_kmp_plugin_version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin_version" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version" }
android-lint = { id = "com.android.lint", version.ref = "agp_version" }

[bundles]
compose = [
    "androidx-compose-runtime",
    "androidx-compose-foundation",
    "androidx-compose-ui",
    "androidx-compose-ui-util",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-lifecycle-runtime-compose",
    "androidx-activity-compose"
]
kotlinx = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android",
    "kotlinx-datetime",
    "kotlinx-collections-immutable"
]
kotlinx-pure = [
    "kotlinx-coroutines-core",
    "kotlinx-datetime",
    "kotlinx-collections-immutable"
]
squareup = [
    "squareup-retrofit",
    "squareup-retrofit-converter-gson",
    "squareup-okhttp",
    "squareup-okhttp-logging-interceptor",
    "squareup-retrofit-adapter-rxjava"
]