[versions]
minSdk = "21"
targetSdk = "35"
compileSdk = "35"
javaVersion = "17"

ksp_version="2.2.0-2.0.2"
kotlin_version="2.2.20"
kotlin_coroutines_version="1.9.0"
koin_bom_version="4.1.1"
# koin_annotations_version="2.2.0"
nav_version="2.5.2"
agp_version="8.9.2"
room_version="2.7.2"
work_version="2.10.2"
compose_bom_version="2025.06.01"
junitVersion = "4.13.2"
junit = "1.3.0"
espressoCoreVersion = "3.7.0"
gson_version = "2.11.0"

[libraries]
# provides the Kotlin Gradle plugin
# This plugin enables Gradle to understand and compile Kotlin code,
# regardless of the target platform (JVM, Android, Multiplatform).
gradleplugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
gradleplugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp_version" }
# gradleplugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
# gradleplugin-composeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "compose" }
gradleplugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp_version" }

androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-preference = "androidx.preference:preference-ktx:1.2.1"

androidx-core-ktx = "androidx.core:core-ktx:1.16.0"

# (Java only)
androidx-work = { group = "androidx.work", name = "work-runtime", version.ref = "work_version" }

# navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "nav_version" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "nav_version" }

# result api
androidx-activity-ktx = "androidx.activity:activity-ktx:1.10.1"
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.8.8"

# room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
# optional - Kotlin Extensions and Coroutines support for Room
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room_version" }
# optional - RxJava support for Room
androidx-room-rxjava = { group = "androidx.room", name = "room-rxjava2", version.ref = "room_version" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom_version" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose" }


# Android misc
android-support-multidex = "com.android.support:multidex:1.0.3"
google-android-material = "com.google.android.material:material:1.4.0"

# TODO еще актуально?
apache-commons = "org.apache.commons:commons-lang3:3.9"

# kotlinx
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin_coroutines_version" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin_coroutines_version" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.3"
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"

# Stetho core
facebook-stetho = "com.facebook.stetho:stetho:1.5.1"

# rxjava
reactivex-rxjava = "io.reactivex.rxjava2:rxjava:2.2.17"
reactivex-rxjava-rxandroid = "io.reactivex.rxjava2:rxandroid:2.1.1"
reactivex-rxjava-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.10.2"

# log
jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"

# koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin_bom_version" }
# Add koin-core dependency to your multiplatform application, for shared Kotlin part:
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }

# koin compose  to your multiplatform application, for use Koin & Compose API
# koin_compose = { module = "io.insert-koin:koin-compose" }
# koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
# koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }

# If you are using pure Android Jetpack Compose, you can go with
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }

# koin annotations
# koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin_annotations_version" }
# koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin_annotations_version" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson_version" }

# retrofit
squareup-retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
squareup-retrofit-converter-gson = "com.squareup.retrofit2:converter-gson:2.9.0"
squareup-okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
squareup-okhttp-logging-interceptor = "com.squareup.okhttp:logging-interceptor:2.6.0"
squareup-retrofit-adapter-rxjava = "com.squareup.retrofit2:adapter-rxjava2:2.4.0"
junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }


[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
android-application = { id = "com.android.application", version.ref = "agp_version" }
android-library = { id = "com.android.library", version.ref = "agp_version" }
#  to enable Kotlin support specifically for Android development
android-kotlin-support = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin_version" }
androidx-navigation-safeargs = { id="androidx.navigation.safeargs", version.ref="nav_version" }
# kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version" }
# TODO после выпила Java
# androidx.navigation.safeargs.kotlin

[bundles]
room = [
    "androidx-room-runtime",
    "androidx-room-ktx",
    "androidx-room-rxjava"
]
compose = [
    "androidx-compose-runtime",
    "androidx-compose-foundation",
    "androidx-compose-ui",
    "androidx-compose-ui-util",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-lifecycle-runtime-compose"
]
kotlinx = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android",
    "kotlinx-datetime",
    "kotlinx-collections-immutable"
]
squareup = [
    "squareup-retrofit",
    "squareup-retrofit-converter-gson",
    "squareup-okhttp",
    "squareup-okhttp-logging-interceptor",
    "squareup-retrofit-adapter-rxjava"
]